.github/workflows/check-pull-request.yml
.github/workflows/cleanup-cache.yml
Cargo.lock
Cargo.toml
pallets/ajuna-affiliates/Cargo.toml
pallets/ajuna-affiliates/README.md
pallets/ajuna-affiliates/src/lib.rs
pallets/ajuna-affiliates/src/mock.rs
pallets/ajuna-affiliates/src/tests.rs
pallets/ajuna-affiliates/src/traits.rs
pallets/ajuna-awesome-avatars/Cargo.toml
pallets/ajuna-battle-mogs/Cargo.toml
pallets/ajuna-nft-staking/Cargo.toml
pallets/ajuna-nft-transfer/Cargo.toml

* Adds the `ajuna-affiliates` pallet
* Minor adjustments

Add affiliates pallet

---

pallets/ajuna-nft-staking/benchmarking/Cargo.toml
pallets/ajuna-nft-staking/benchmarking/src/lib.rs
pallets/ajuna-nft-staking/src/contracts.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/accept.rs
pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/snipe.rs
pallets/ajuna-nft-staking/src/tests/mock.rs

This PR updates the `pallet-ajuna-staking` to match the latest codebase found in the https://github.com/ajuna-network/Ajuna repository.

[Staking] Update pallet to latest codebase

---

pallets/ajuna-awesome-avatars/benchmarking/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/mod.rs
pallets/ajuna-awesome-avatars/src/migration/v6.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v1.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/flask.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
pallets/ajuna-awesome-avatars/src/types/config.rs

This PR updates the pallet-ajuna-staking to match the latest codebase found in the https://github.com/ajuna-network/Ajuna repository.

[AAA] Update pallet to latest codebase

---

Cargo.lock
Cargo.toml
pallets/ajuna-awesome-avatars/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/src/mock.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs

This PR performs the initial integration between the `pallet-ajuna-affiliates` and the `pallet-ajuna-awesome-avatars` pallets.

[Affiliates] Initial integration with AAA

---

Cargo.lock
pallets/ajuna-affiliates/src/lib.rs
pallets/ajuna-affiliates/src/traits.rs
pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/benchmarking/src/mock.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v6.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/affiliates.rs
pallets/ajuna-awesome-avatars/src/types/config.rs
pallets/ajuna-awesome-avatars/src/types/mod.rs

Implementens the specifications described in:
* https://ajunanetwork.atlassian.net/browse/AJUN-132
* https://ajunanetwork.atlassian.net/browse/AJUN-187

[AJUN-132/AJUN-187] Pallet Affiliates integration phase 2

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v6.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v1.rs
pallets/ajuna-awesome-avatars/src/types/fee.rs
pallets/ajuna-awesome-avatars/src/types/season.rs

Applies changes described [here](https://ajunanetwork.atlassian.net/wiki/spaces/PLATFORM/pages/225181697/Season+Config+changes)

[AJUN-197] Season config changes

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v6.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/account.rs

Applies changes described [here](https://ajunanetwork.atlassian.net/wiki/x/AwBwDQ)

 [AJUN-198] PlayerSeasonConfig changes

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v6.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/config.rs

Applies fixes described in https://ajunanetwork.atlassian.net/browse/ABO-241

[ABO-241] Wrong structure for transfer config

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/account.rs
pallets/ajuna-awesome-avatars/src/types/config.rs

Implement changes described in https://ajunanetwork.atlassian.net/browse/ABO-242
Additionally adds logic to handle the unlocking elements

[ABO-242] Unlock logic + structure

---

Cargo.lock
pallets/ajuna-awesome-avatars/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/src/mock.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tournament.rs

This PR integrates the code developed in #14 into the AAA pallet.

[AJUN-3] Pallet Chapters/Tournaments Integration into AAA

---

.github/workflows/check-pull-request.yml
Cargo.lock
Cargo.toml
pallets/ajuna-tournament/src/mock.rs
pallets/ajuna-wildcard/Cargo.toml
pallets/ajuna-wildcard/src/asset.rs
pallets/ajuna-wildcard/src/lib.rs
pallets/ajuna-wildcard/src/tests/ext/challenge.rs
pallets/ajuna-wildcard/src/tests/ext/deposit.rs
pallets/ajuna-wildcard/src/tests/ext/end2end.rs
pallets/ajuna-wildcard/src/tests/ext/freeze.rs
pallets/ajuna-wildcard/src/tests/ext/mod.rs
pallets/ajuna-wildcard/src/tests/ext/propagate_freeze.rs
pallets/ajuna-wildcard/src/tests/ext/refund_frozen.rs
pallets/ajuna-wildcard/src/tests/ext/respond_challenge.rs
pallets/ajuna-wildcard/src/tests/ext/respond_zero_challenge.rs
pallets/ajuna-wildcard/src/tests/ext/withdraw.rs
pallets/ajuna-wildcard/src/tests/ext/withdraw_frozen.rs
pallets/ajuna-wildcard/src/tests/mock.rs
pallets/ajuna-wildcard/src/tests/mod.rs

Adds the pallet `ajuna-wildcard` to the repository extracted from https://github.com/ajuna-network/Ajuna/tree/develop-erdstall

[Wildcard] Add ajuna-wildcard pallet to repo

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tournament.rs
pallets/ajuna-tournament/src/lib.rs
pallets/ajuna-tournament/src/tests.rs
pallets/ajuna-tournament/src/traits.rs

* Added additional methods and checks to ensure that ranking and price claiming can only be performed at the correct tournament periods.
* Added test to verify that duplicated entities cannot be ranked together

[Tournament] Logic adjustments

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v3.rs

Adds V3 logic for avatar minting/forging as base copy of V1

[AJUN-227] Add Logic Forge & Mint v3 for BBB

---

pallets/ajuna-tournament/src/lib.rs

Solves the bug described in https://ajunanetwork.atlassian.net/browse/AJUN-242

[AJUN-242] Bugfix GoldenDuck event

---

pallets/ajuna-awesome-avatars/src/lib.rs

* Adds logic to take a part of the fees as stated in the tournament config `take_fee_percentage` into AAA mint process

[AJUN-243] Mint Fees for Tournant doesn't work

---

pallets/ajuna-awesome-avatars/src/types/avatar/force.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tournament.rs
pallets/ajuna-tournament/src/lib.rs
pallets/ajuna-tournament/src/mock.rs
pallets/ajuna-tournament/src/traits.rs

* Expands the `AvatarRankingCategory` enum to provide more ranking categories

[AJUN-278] Ranker Improvement

---

.cargo/zepter.yaml
Cargo.lock
orml-pallets-benchmarking/Cargo.toml
pallets/ajuna-affiliates/Cargo.toml
pallets/ajuna-awesome-avatars/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/Cargo.toml
pallets/ajuna-battle-mogs/Cargo.toml
pallets/ajuna-board/Cargo.toml
pallets/ajuna-matchmaker/Cargo.toml
pallets/ajuna-nft-staking/Cargo.toml
pallets/ajuna-nft-transfer/Cargo.toml
pallets/ajuna-tournament/Cargo.toml
pallets/ajuna-wildcard/Cargo.toml

* Adds config for the `zepter` tool
* Adjusting missing features and reorders existing ones

Add zepter config and fix features

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v4.rs

Adds code skeleton for future avatar logic V4

[AJUN-302] Create version 4 Mint and Forge

---

Cargo.lock
Cargo.toml
pallets/ajuna-board/Cargo.toml
pallets/ajuna-wildcard/src/lib.rs

* Updates dependencies to polkadot v1.12.0

[AJUN-435] Update to polkadot v1.12.0

---

Cargo.lock
Cargo.toml

* Updates dependencies to polkadot-sdk `1.13.0`

[AJUN-517] Update ajuna-pallets to polkadot v1.13.0

---

pallets/ajuna-awesome-avatars/src/types/avatar/versions/v3.rs

[V3] Logic fix
